cds-snc/cds-superset

.github/workflows/containers-apply.yml, .github/workflows/containers-pr.yml, .github/workflows/tf-apply.yml, .github/workflows/tf-plan.yml
Fixes action names because I forgot to update them when I created the yml files
=> fix: action names

common/common_variables.tf, terragrunt/.terraform.lock.hcl, terragrunt/certificate.tf, terragrunt/ecs.tf, terragrunt/load_balancer.tf, terragrunt/route53.tf, terragrunt/terragrunt.hcl, terragrunt/vpc.tf
Add a load balancer and Route53 hosted zone to hold the Superset records.
=> feat: add load balancer and route53

terragrunt/ecs.tf
Update the Superset task definition to allow the for direct command execution against the running Superset container.
=> feat: allow ECS task exec

Makefile, README.md, containers/superset_config.py, databases/athena_costing_data.yml, terragrunt/athena_iam.tf
Update the Athena IAM role with needed permissions.
Add connection details for the Athena database connection.
Update the README with setup steps.
- https://github.com/cds-snc/cds-superset/issues/21
=> fix: Athena read role permissions

.github/workflows/containers-deploy.yml, terragrunt/ecs.tf
Update the container deploy workflow to also update the Celery worker/beat services.
Update the Celery worker service to lower resources to save costs.
- https://github.com/cds-snc/platform-core-services/issues/536
=> feat: deploy celery worker/beat Docker images

containers/superset_config.py
Update the Superset config to fix the RateLimit config.  Also incudes cache warming via a CeleryBeat config.
- Closes https://github.com/cds-snc/platform-core-services/issues/536
=> feat: update RateLimit and CeleryBeat config

terragrunt/data_export.tf
Remove the product export role as the proof-of-concept has been finished.
- https://github.com/cds-snc/platform-core-services/issues/552
=> chore: remove product export role

containers/superset_config.py
Update the cookie settings and switch to using server-side managed sessions to improve security.
=> fix: improve session security settings

containers/superset_config.py
Add a custom ReadOnly role to test Flask AppBuilder role creation.
- https://github.com/cds-snc/platform-core-services/issues/605
=> feat: create ReadOnly role

terragrunt/athena_iam.tf
Update the Superset IAM read role to limit it to specific data catalogs and databases within the data lake.
⚠️ This was applied locally to test.
- https://github.com/cds-snc/platform-core-services/issues/610
=> fix: limit Superset read access in the Data Lake

.github/workflows/tf-apply-prod.yml, .github/workflows/tf-apply-staging.yml, .github/workflows/tf-plan-prod.yml, .github/workflows/tf-plan-staging.yml, terragrunt/aws/ecs.tf, terragrunt/env/staging/.terraform.lock.hcl, terragrunt/env/staging/env_vars.hcl, terragrunt/env/staging/terragrunt.hcl
Add the Terragrunt config and workflows to create the Staging environment.
:warning: Note this was applied locally to fix issues with the celery tasks and shared ECS cluster.
=> feat: staging environment config

terragrunt/aws/waf.tf
Update the WAF ACL so that the PUT requests to save a large dashboard are not blocked.
- https://github.com/cds-snc/platform-core-services/issues/650
=> fix: stop WAF from blocking dashboard saves

databases/operations_aws.yml
Update the database connection export with the new dedicated IAM role.
- https://github.com/cds-snc/platform-core-services/issues/649
=> chore: update Operations / AWS DB export

terragrunt/env/staging/terragrunt.hcl
Allow Staging to access the aggregate Freshdesk ticket dataset.
- https://github.com/cds-snc/platform-core-services/issues/621
- https://github.com/cds-snc/data-lake/pull/111
=> feat: grant Staging access to Freshdesk dataset

databases/platform_support.yml
Add the database configuration export for the new `Platform / Support` connection.
- https://github.com/cds-snc/platform-core-services/issues/621
=> chore: add Platform / Support database export

terragrunt/aws/waf.tf
Update the WAF ACL so that its `SizeRestriction_BODY` rule does not block API requests while working with large dashboards.
=> fix: allow API requests for large dashboards

terragrunt/env/staging/terragrunt.hcl
Allow Staging to access a sample of Salesforces dataset (account + opportunity basic info)
- https://github.com/cds-snc/platform-core-services/issues/646
- Blocks https://github.com/cds-snc/data-lake/pull/132
=> feat: grant staging access to Salesforces sample tables

docker/superset_config.py
Pushing the limit to 100k to test capacity
=> fix: increase Superset meta db row limit to 100k

.github/workflows/docker-apply-prod.yml, .github/workflows/docker-apply-staging.yml, terragrunt/aws/ecs.tf
Update to ARM64 for cost and performance.  Also adjusts the ECS superset and celery worker resources as more queries will now be running asynchronously on the workers.
- https://github.com/cds-snc/platform-core-services/issues/689
=> feat: switch to ARM64 Docker images

.github/workflows/docker-apply-staging.yml
Update the SBOM scan to request the correct architecture.
=> fix: docker SBOM architecture

terragrunt/env/prod/terragrunt.hcl
Add the IAM role that will be used to access prod GC Forms data.
⚠️  Note this will have not change in Staging and will only take effect once the change is released to Prod.
- https://github.com/cds-snc/platform-core-services/issues/648
=> feat: create GC Forms data IAM role

docker/superset_config.py
Add the permission that will allow users to filter data on time ranges.
=> fix: add missing API time range permission

.github/workflows/tf-apply-prod.yml, .github/workflows/tf-apply-staging.yml, .github/workflows/tf-plan-prod.yml, .github/workflows/tf-plan-staging.yml, terragrunt/aws/alarms.tf, terragrunt/aws/variables.tf
Add a CloudWatch alarm and log insight queries so that the team is notified when privileged roles are granted to users.
- https://github.com/cds-snc/platform-core-services/issues/759
=> feat: add alarm for privileged role grants

terragrunt/env/prod/terragrunt.hcl, terragrunt/env/staging/terragrunt.hcl
Creating IAM role for the new GCDS tables
=> feat: add GCDS tables

docker/Dockerfile, docker/static/assets/system-use.js, docker/superset/static/assets/system-use.js, docker/superset/templates/tail_js_custom_extra.html
Add a system use notification to meet NIST control AC-8.  The notification is locale aware and lets the user know that Superset is a GC system and should only be accessed by authorized individuals.
- https://github.com/cds-snc/superset-system-level-security-controls/issues/7
=> feat: add system use notification

.github/workflows/backstage-catalog-helper.yml, .github/workflows/dependency-review.yml, .github/workflows/dependency-security-update.yml, .github/workflows/docker-apply-prod.yml, .github/workflows/docker-apply-staging.yml, .github/workflows/docker-deploy-prod.yml, .github/workflows/docker-deploy-staging.yml, .github/workflows/docker-pr.yml, .github/workflows/docker-vulnerability-scan.yml, .github/workflows/export_github_data.yml, .github/workflows/labels.yml, .github/workflows/ossf-scorecard.yml, .github/workflows/s3-backup.yml, .github/workflows/shellcheck.yml, .github/workflows/tf-apply-prod.yml, .github/workflows/tf-apply-staging.yml, .github/workflows/tf-drift-check-prod.yml, .github/workflows/tf-drift-check-staging.yml, .github/workflows/tf-plan-prod.yml, .github/workflows/tf-plan-staging.yml, .github/workflows/tf-static-scan.yml, .github/workflows/workflow-failure.yml, .github/workflows/workflow-pr.yml
Update the workflows based on scan results from zizmor.
=> fix: add workflow security fixes

docker/superset_config.py
adding custom color pallet https://github.com/cds-snc/platform-core-services/issues/816
=> feat: add custom colors

.github/workflows/workflow-failure.yml, terragrunt/aws/database.tf
Update the Terraform so it matches the current Postgres version.
Fix the workflow failure Slack message display to include the correct workflow name and URL.
=> fix: sync Terraform with RDS version
