cds-snc/cds-superset

- terragrunt/main.tf
The custom image is the same as the base superset image with one small difference it includes the superset_config.py file which will be needed to configure the solution. The config currently does nothing but write out a log.
> feat: use the custom image for superset

- containers/superset_config.py
- in-memory cache
- no workers for long running queries.
> feat: add a simple simple_config

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/database.tf
- terragrunt/ecs.tf
- terragrunt/terragrunt.hcl
- terragrunt/variables.tf
Add a two instance Postgres Aurora RDS cluster to hold Superset's app data and configuration data.
> feat: add RDS cluster for Superset data

- containers/Dockerfile
- containers/superset_config.py
- terragrunt/ecs.tf
Update the Superset config to include an Examples database URI.  This allows for the example data to be loaded with the following command:
```
superset load_examples --force
```
> feat: setup Examples database and config

- containers/superset_config.py
Adds a function the configuration that allows us to set the prefix and the timeout for all available cache types in superset.
> feat: enable redis caching in container

- terragrunt/ecs.tf
Since we are having network issues and the docs have a part this adds a port to the configuration in the hopes it will work.
https://superset.apache.org/docs/installation/cache/
> fix: add a port to redis URL in config

- containers/superset_config.py
- terragrunt/ecs.tf
Update the ECS task and Superset config to specify the Redis URL in the expected format.
> fix: Redis cache URL and env var key

- containers/requirements.txt
Superset has a constraint on the Redis package being `< 5.0`.
> fix: Python Redis package version

- .github/workflows/tf-plan.yml
- Makefile
- modules/aws/redis/input.tf
- terragrunt/glue.tf
Imports a click-opsed glue crawler and athena table into terraform.
This should have all resources created,
One known exclusion because I'm tired and I didn't want to import it was the query bucket for athena database.
- On draft until we add import to terraform-plan
> feat: import glue crawler and athena table

- containers/requirements.txt
- containers/superset_config.py
Add `pyathena[pandas]` to allow for Athena datasources.  The version selected is the highest compatible as listed in [Superset's setup.py](https://github.com/apache/superset/blob/71a950fc803898393fbe1c0b370aaca438eeb38b/setup.py#L139). 
- https://github.com/cds-snc/cds-superset/issues/21
> feat: add `pyathena[pandas]` to support Athena datasources

- terragrunt/athena_iam.tf
- terragrunt/ecs.tf
- terragrunt/glue.tf
Add the IAM role that will be assumed by the ECS
Superset task to read from Athena and its associated S3 buckets.
Remove the `import` statements as they have now been applied.
- https://github.com/cds-snc/cds-superset/issues/21
> feat: superset IAM role to read from Athena

- terragrunt/athena_iam.tf
- terragrunt/ecs.tf
Update the Athena IAM role's assume policy to use the ECS module's output to create an implicit dependency and avoid hardcoding.
- https://github.com/cds-snc/cds-superset/issues/21
> chore: switch to ECS module's task role ARN output

- .github/workflows/containers-apply.yml
- .github/workflows/containers-deploy.yml
- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- containers/Dockerfile
- containers/superset_config.py
- terragrunt/ecr.tf
- terragrunt/ecs.tf
Add a GitHub workflow that deploys the newly build Superset
Docker image after it is built and pushed.
Add an ECR policy that removes old Docker images.
- Closes https://github.com/cds-snc/platform-core-services/issues/534
> feat: add workflow to deploy updated Superset image

- terragrunt/ecs.tf
- terragrunt/vpc.tf
Update the superset ECS service to include service discovery.
This is being done in preparation for the Celery worker and beat services.
- https://github.com/cds-snc/platform-core-services/issues/536
> feat: add service discovery to the superset service

- terragrunt/ecs.tf
Add Celery worker/beat services to the Superset cluster.  These will be used to handle longer running SQL queries and schedule cleanup jobs.
- https://github.com/cds-snc/platform-core-services/issues/536
> feat: add Celery worker and beat services

- containers/docker-bootstrap.sh
- terragrunt/ecs.tf
Add standalone ECS task that can upgrade the Superset database and re-initialize roles.  This task will be invoked via a GitHub workflow when a new Superset Docker image is deployed.
- https://github.com/cds-snc/platform-core-services/issues/539
> feat: add ECS task to upgrade Superset

- .github/workflows/containers-deploy.yml
Update the container deploy workflow to run the
Superset database upgrade commands after
deployment.
- Closes https://github.com/cds-snc/platform-core-services/issues/539
> feat: upgrade Superset after image deploy

- containers/superset_config.py
Update the config to use the default value of the request's IP address as the rate limiter key.
> fix: remove request identifier configuration

- terragrunt/ecs.tf
Update the services to include CPU and memory autoscaling policies.
Update Celery to run 2 workers by default to test that things behave as expected with multiple workers.
> feat: add autoscaling for Superset and Celery workers

- terragrunt/ecs.tf
Lower the Celery worker task count to 1 to save on costs.
Confirmed with the last PR that Celery workers are discovering each other as expected:
```
[2024-02-07 22:21:45,620: INFO/MainProcess] mingle: sync complete
[2024-02-07 22:21:45,620: INFO/MainProcess] mingle: sync with 2 nodes
[2024-02-07 22:21:44,612: INFO/MainProcess] sync with celery@ip-10-0-0-0.ca-central-1.compute.internal
[2024-02-07 22:21:44,612: INFO/MainProcess] sync with celery@ip-10-0-0-0.ca-central-1.compute.internal
[2024-02-07 22:21:44,590: INFO/MainProcess] Connected to redis://some-cluster-address:6379/0
[2024-02-07 22:21:44,595: INFO/MainProcess] mingle: searching for neighbors
```
- #47
> chore: lower Celery task count

- terragrunt/data_export.tf
Add the resources required to start exporting Notify database snapshots to an S3 bucket.  Currently this data export is being invoked manually from the Notify account, but in the figure the flow would be as follows:
1. Create a scheduled job that used the `DataExportSupersetReadSnaphots` role in the CDS-Superset account.
2. It will assume the `DataExportSupersetReadSnaphots` role in the Notify account.
3. An RDS export to S3 will be started which uses the KMS key and S3 bucket in the CDS-Superset account to encrypt and store data.
These are being tested via local TF apply, hence the lack of TF plan.
> feat: data export from Notify

- terragrunt/data_export.tf
- terragrunt/glue.tf
Add a crawler for Notify data exports.
This was applied locally to test.
> feat: add AWS Glue crawler for Notify data

- terragrunt/data_export.tf
- terragrunt/glue.tf
Add an IAM role that can be used by the Glue ETL jobs.
> feat: Glue ETL IAM role

- terragrunt/glue.tf
Update the Glue billing data crawler so that it runs on the first day of each month.
This will create the month's new partition key in the data.
> fix: run billing crawler on first day of the month

- terragrunt/glue.tf
Update the Notify data crawler to consider table schemas when determining if a new or existing table should be used.
⚠️  This was applied locally to test.
> fix: Notify data crawler ignore S3 path

- terragrunt/glue.tf
Remove the schema grouping by S3 path as this was causing all exported tables to be added to the same Glue table since they shared a common root path.
> fix: remove Notify crawler schema grouping

- terragrunt/athena_iam.tf
Update the Superset IAM policy to prevent read of the exported RDS tables that have not been processed by the Glue ETL job.
If we go forward with this, it would make sense to have the exported tables in a database that only Glue has access to.
> fix: block Superset access to export data

- terragrunt/data_export.tf
- terragrunt/glue.tf
Add a new product role ARN that is allowed to perform cross account RDS to S3 data exports.
- https://github.com/cds-snc/platform-core-services/issues/552
> feat: add new product role for data export

- terragrunt/ecs.tf
The default gunicorn keepalive is 2s which is leading to intermittent 502 errors.  Since gunicorn is running behind an ALB it makes sense to set this higher.
Here is the error appearing that this should fix:
- https://github.com/apache/superset/pull/20348
- https://docs.gunicorn.org/en/stable/settings.html#keepalive
> fix: increase gunicorn timeout to deal with 502 errors

- .devcontainer/devcontainer.json
- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/database.tf
Upgrade to the latest RDS module, which changes to standalone security group rules.
This PR makes sure they are imported properly as Terraform does not handle inline SG rule changes well.
Also includes an update to Terraform and Terragrunt versions.
- https://github.com/cds-snc/terraform-modules/pull/481
> chore: upgrade to latest RDS module

- terragrunt/ecs.tf
Update the Superset database upgrade task to prevent it from being recreated on each Terraform apply.
> chore: stop ECS upgrade task recreate

- .github/workflows/containers-apply.yml
- .github/workflows/docker-vulnerability-scan.yml
Update the Docker scan actions to use a self-hosted Trivy vulnerability database. This is being done to address the rate limiting of the publicly hosted database.
- https://github.com/cds-snc/platform-core-services/issues/597
> fix: use CDS Trivy vulnerability database

- containers/Dockerfile
Upgrade to the latest 4.0.2 Superset release.
- https://github.com/cds-snc/platform-core-services/issues/603
> chore: upgrade to Superset v4

- terragrunt/redis.tf
Remove the `moved` blocks as the state migration has been completed and these are no longer needed.
- Closes https://github.com/cds-snc/platform-core-services/issues/604
> chore: remove Redis `moved` blocks

- terragrunt/glue.tf
Update the Glue crawlers path and IAM permissions to properly reference the Cost and Usage Report v2.0 export.
⚠️ Note that these fixes were applied locally.
- https://github.com/cds-snc/platform-core-services/issues/601
> fix: CUR path and permissions

- containers/requirements.txt
Update to latest Flask-Session to fix an issue with using server-side user sessions.  This is being caused by Superset 4.0.2 using Werkzeug 3.0.0, which is not compatible with Flask-Session 0.5.0.
The error being thrown on server startup is:
```
TypeError: cannot use a string pattern on a bytes-like object
```
- https://github.com/apache/superset/issues/29695
> fix: Flask-Session 0.5.0 incompatibility with Werkzeug 3.0.0

- .github/workflows/tf-apply.yml
- .github/workflows/tf-plan.yml
- terragrunt/alarms.tf
- terragrunt/kms.tf
- terragrunt/sns.tf
- terragrunt/variables.tf
Add CloudWatch alarms to monitor ECS resource use, load balancer health and errors logged.
This includes the SNS topic/subscriptions and KMS key required to publish the alarms to Slack.
- https://github.com/cds-snc/platform-core-services/issues/606
> feat: add CloudWatch alarms

- terragrunt/waf.tf
Add a WAF ACL for the Superset load balancer.  Logging will be setup in a future PR.
- https://github.com/cds-snc/platform-core-services/issues/614
> feat: add firewall for Superset load balancer

- common/common_variables.tf
- terragrunt/alarms.tf
- terragrunt/athena.tf
- terragrunt/load_balancer.tf
- terragrunt/terragrunt.hcl
- terragrunt/waf.tf
Update the WAF ACL and load balancer to send their logs to the Cloud Based Sensor satellite bucket.
Create the Athena workgroup and database required to query these logs.
Fix a typo in one of the alarm descriptions.
- https://github.com/cds-snc/platform-core-services/issues/614
> feat: enable LB and WAF ACL logging

- terragrunt/alarms.tf
Update the alarm descriptions to remove the icons as these are making it harder to determine if it is an `ERROR` or `OK` action alarm triggered.
> fix: remove icons from alarm descriptions

- terragrunt/alarms.tf
Update the CloudWatch alarm error filter to ignore a non-user impacting bug with Superset.
> chore: suppress false positive Superset alarm

- terragrunt/waf.tf
Add the WAF IP blocklist module which will automatically block an IP address that reaches a threshold of `BLOCK` WAF requests.  
The IP block is temporary and will be reset after 24 hours of the IP address being below the `BLOCK` request threshold.
- Closes https://github.com/cds-snc/platform-core-services/issues/614
> feat: add WAF IP blocklist

- terragrunt/athena_iam.tf
Update Superset's Athena IAM role to allow it to access the `Transformed`, `Curated` and `Athena` query result buckets in the data lake account.
- https://github.com/cds-snc/platform-core-services/issues/610
> feat: update Superset Athena role to allow data lake

- terragrunt/alarms.tf
- terragrunt/ecs.tf
Increase the vCPU to 2 and raise the alarm threshold for resource use.  This will reduce the number of resource alarms we have been seeing for low use patterns.
> fix: adjust Superset ECS resources

- terragrunt/waf.tf
Update the WAF IP blocklist module to also consider load balancer 4xx responses as a reason to block IP addresses.
- https://github.com/cds-snc/terraform-modules/pull/593
> feat: update to block based on LB 4xx responses

- terragrunt/alarms.tf
Increase the LB response time alarm threshold so that the alarm triggers after 3 datapoints within a 5 minute period with a response time > 2 seconds.
This is being done because the Superset dashboard load can be slow for non-cached query results.
> fix: raise threshold for load balancer response time alarm

- .github/workflows/docker-deploy.yml
- docker/Dockerfile
Update the Docker deploy workflow so that its triggering workflow's name is correct.
Also make a minor Docker image change to trigger a redeploy and DB upgrade.
> fix: docker deploy workflow name trigger

- docker/superset_config.py
Update the `ReadOnly` role so that it can access all data sources.  This may be scaled back as we add more data sources.
- https://github.com/cds-snc/platform-core-services/issues/626
> fix: ReadOnly role data access

- docker/superset_config.py
Update the CSRF exemption list so that cache warming requests do not require a CSRF token.  This has a low risk is it would only allow CSRF attacks to the cache warming API endpoint.
Additionally, this adds a dashboard cache warming strategy as well and increases the cache warming frequency to every 2 hours.
- https://github.com/cds-snc/platform-core-services/issues/628
> fix: skip CSRF checks on cache warm up requests

- terragrunt/alarms.tf
- terragrunt/ecs.tf
Update the CloudWatch alarm filters to avoid triggering an alarm when the user has caused a generic DB error.  These are caused by query syntax issues.
> fix: suppress all generic DB errors

- .github/workflows/labels.yml
- .github/workflows/scripts/check-workflow-run-trigger.sh
- .github/workflows/workflow-pr.yml
Add a workflow that checks if a PR changing a workflow has valid workflow_run triggers.  This is to catch breaking changes between dependent workflows.
- Closes https://github.com/cds-snc/platform-core-services/issues/640
> feat: add workflow to validate PRs against workflows

- terragrunt/aws/route53.tf
- terragrunt/env/common/common_variables.tf
- terragrunt/env/prod/env_vars.hcl
- terragrunt/env/terragrunt.hcl
Add a new Prod `superset.alpha.canada.ca` hosted zone as part of the Staging environment setup.  This will help reduce the downtime of the switch.
> feat: create new Production hosted zone

- terragrunt/aws/route53.tf
Updating the production url to be a subdomain of the cds-snc.ca domain as this is an internal tool. This will be a new pattern going forward for tools that are only for CDS use.
As with the previous domain migration this is step 1 of 2 to minimize downtime during the switch.
> fix: switch prod URL to superset.cds-snc.ca

- terragrunt/aws/oidc.tf
Create a new OIDC role that is able to operate on workflows triggered by releases.
- https://github.com/cds-snc/cds-superset/pull/232
> feat: add an OIDC role that can perform prod releases

- .github/CODEOWNERS
- .github/workflows/docker-apply-prod.yml
- .github/workflows/docker-apply-staging.yml
- .github/workflows/docker-deploy-prod.yml
- .github/workflows/docker-deploy-staging.yml
- .github/workflows/docker-pr.yml
- .github/workflows/tf-apply-prod.yml
- .github/workflows/tf-plan-prod.yml
- .github/workflows/workflow-failure.yml
Update the Production Docker and Terraform workflows to trigger when a release is published.  The Staging workflows will continue to trigger on pushes to `main`.
Add a workflow failure notifier so we get notified when a workflow has an error.
> feat: split Staging and Prod deploy workflows

- release-please-config.json
Update the release please config so that `chore` commits trigger the release process.
> fix: release please to trigger release for chore commits

- terragrunt/aws/database.tf
- terragrunt/aws/variables.tf
- terragrunt/env/prod/terragrunt.hcl
- terragrunt/env/staging/terragrunt.hcl
Change from provisioned database instances to a serverless instances. This will save cost and allow us to scale with use.
For now, we will run using a single writer instance to see how performance is.
> feat!: switch to Aurora Serverless database

- terragrunt/aws/alarms.tf
Update the CloudWatch `ERROR` alarm filter to ignore "DML not allowed" errors.  These are caused by user entered queries and do not require our attention as the error message displayed to the user is clear:
```
superset.exceptions.SupersetErrorsException: [SupersetError(message='This database does not allow for DDL/DML, and the query could not be parsed to confirm it is a read-only query. Please contact your administrator for more assistance.', error_type=<SupersetErrorType.DML_NOT_ALLOWED_ERROR: 'DML_NOT_ALLOWED_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'issue_codes': [{'code': 1022, 'message': 'Issue 1022 - Database does not allow data manipulation.'}]})]
```
> chore: suppress DML not allowed CloudWatch errors

- .github/workflows/docker-apply-prod.yml
The SBOM generated for the production release is not required as GitHub does not consider its results since it is created for a tag and not the default branch.
The most recent dependency graph will always be updated with every merge to `main` that includes Docker changes.
> fix: remove SBOM generate for prod release

- .devcontainer/devcontainer.json
- .github/workflows/tf-apply-prod.yml
- .github/workflows/tf-apply-staging.yml
- .github/workflows/tf-plan-prod.yml
- .github/workflows/tf-plan-staging.yml
- terragrunt/env/terragrunt.hcl
Upgrade Terraform and switch to the new `.tflock` file to manage state locking rather than a DynamoDB table.
> chore: update to latest Terraform and use lockfile

- terragrunt/aws/athena_iam.tf
- terragrunt/env/staging/.terraform.lock.hcl
Update the Staging Superset Athena access to allow it to query the test GC Forms form data.
⚠️ Changes were applied locally to test.
- https://github.com/cds-snc/platform-core-services/issues/648
- https://github.com/cds-snc/data-lake/pull/62
> feat: staging access to GC Forms form test data

- terragrunt/aws/alarms.tf
Update the `ERROR` alarm filter to ignore errors caused by a user writing and testing queries.
> chore: suppress user query CloudWatch alarms

- docker/superset_config.py
Allow for the use of defined Jinja variables and templating in SQL Labs.
https://superset.apache.org/docs/configuration/sql-templating/
> feat: enable Jinja templating in queries

- terragrunt/aws/athena_iam.tf
- terragrunt/aws/variables.tf
- terragrunt/env/prod/terragrunt.hcl
- terragrunt/env/staging/terragrunt.hcl
Add a dedicated IAM role that is used by Superset to connect to each AWS Glue database.  This is being done to give us finer control over which databases are visible to a user.
- https://github.com/cds-snc/platform-core-services/issues/649
- https://github.com/cds-snc/data-lake/pull/71
> feat: create IAM role per Glue database

- terragrunt/aws/athena_iam.tf
Update the GlueRead IAM policy so that its `sid` attribute does not contain non alphanumeric characters.
⚠️ This was applied locally to test.
- https://github.com/cds-snc/platform-core-services/issues/649
> fix: non-alpha characters in IAM policy sid

- terragrunt/aws/alarms.tf
We're seeing cases were non-user related actions are causing this error to be thrown by Superset.  For example, the following is thrown when a query consumes too much memory:
```
superset.exceptions.SupersetErrorsException: [SupersetError(message="command not allowed when used memory > 'maxmemory'.", error_type=<SupersetErrorType.GENERIC_DB_ENGINE_ERROR: 'GENERIC_DB_ENGINE_ERROR'>, level=<ErrorLevel.ERROR: 'error'>, extra={'engine_name': 'Amazon Athena', 'issue_codes': [{'code': 1002, 'message': 'Issue 1002 - The database returned an unexpected error.'}]})]
```
As a result, we'll remove the generic suppression and re-add user-related error suppressions as they come up.
- https://github.com/cds-snc/platform-core-services/issues/657
> fix: remove suppress of generic DB errors

- terragrunt/aws/alarms.tf
These AccessDenied database errors are caused by a user attempting to query a Glue database table they do not have access to.
> chore: suppress AccessDenied DB errors

- terragrunt/aws/alarms.tf
Suppress CloudWatch alarm for user attempting to run a non SELECT statement in the SQL Lab editor.
> chore: suppress user generated error

- terragrunt/env/prod/terragrunt.hcl
Allow Superset prod to access the Freshdesk dataset.
⚠️  It is expected that there are no changes as this only applies to the production environment.
- https://github.com/cds-snc/platform-core-services/issues/621
> feat: onboard Freshdesk dataset to prod

- docker/superset_config.py
Update the ReadOnly role to include the explore permissions required to view and interact with calendar heatmap charts.
- https://github.com/apache/superset/discussions/30542
> fix: add missing `explore` permissions to ReadOnly role

- docker/superset/integration_tests/database.py
Update the database integration tests so that they do not attempt to run against databases that require user impersonation.
- https://github.com/cds-snc/platform-core-services/issues/639
> fix: integration tests for impersonation databases

- terragrunt/aws/alarms.tf
Suppress the error a user receives when they run a SQL labs query without selecting the proper database.
> chore: suppress user query error

- terragrunt/aws/alarms.tf
Suppress CloudWatch alarms for the following recoverable user error:
```
Column 'field_name' contains non-numeric values
```
> chore: suppress user query errors

- terragrunt/aws/kms.tf
- terragrunt/aws/sns.tf
Add new SNS topics to handle alarm notifications
in `us-east-1`.
- https://github.com/cds-snc/platform-core-services/issues/667
> feat: add SNS alarm topics in us-east-1

- .github/workflows/tf-apply-prod.yml
- .github/workflows/tf-apply-staging.yml
- .github/workflows/tf-plan-prod.yml
- .github/workflows/tf-plan-staging.yml
- terragrunt/aws/variables.tf
- terragrunt/aws/waf.tf
The status checker's IP address is occasionally being identified as in the US so we're adding a secret Upptime request header that will allow those requests to succeed.
> fix: update CA geo restriction with Upptime header

- terragrunt/aws/alarms.tf
Add a new CloudWatch alarm that triggers if more than a specified threshold of warnings have been reported.
Also adjust the error alarm to suppress more user generated errors.
> fix: add warning CloudWatch alarm

- .github/workflows/docker-deploy-prod.yml
- .github/workflows/docker-deploy-staging.yml
Update the ECS task deployment action so that tags are propagated.
This has been causing a minor Terraform plan filp/flop when Terraform apply is run after this action since it has been unsetting the value.
> fix: propagate tags on new deployments

- terragrunt/aws/alarms.tf
- terragrunt/aws/athena_iam.tf
Update the IAM permissions to allow asynchronous queries to be run by the Celery workers.  Currenly, queries can only be run synchronously by the Superset ECS task, which is resulting in performance impacts and slower response times.
Update the CloudWatch alarms to suppress more user generated errors from queries run in SQL labs.
> fix: allow Celery works to perform async queries

- docker/superset_config.py
Increase row limit for Superset Meta DB to 10k to test larger queries
> feat: setup superset meta db limit to 10000

- docker/superset_config.py
- terragrunt/aws/alarms.tf
Reduce the Superset meta database limit back to its default value.  This is the number of rows that will be scanned from a table before joining and aggregation occurs (lower = less memory usage).
Update the alarms with a few more user generated error message from SQL labs.
> revert: meta database limit to default value

- terragrunt/aws/alarms.tf
Update the list of CloudWatch alarms to suppress caused by user generated SQL query errors.
> chore: suppress user generated alarms

- docker/superset_config.py
This role will be granted to members of the Platform business unit.
It will be used to grant users access to Platform specific dashboards.
> feat: add `PlatformUser` role

- terragrunt/aws/waf.tf
Update the WAF IP blocklist to the latest version up allow 405, 410 and 422 responses from users.  These are returned occasionally by Superset for legitimate requests and should not cause the user's IP to be blocked.
> feat: allow some 4XX resonses through the IP blocklist

- docker/superset_config.py
Update the CacheWarmer role so that it has access to all datasources. Without this, it cannot properly query data and preload the cache.
> fix: allow CacheWarmer access to all data

- .github/workflows/release-please.yml
Update the release please workflow to use a new, dedicated GitHub app for releases.
- https://github.com/cds-snc/platform-core-services/issues/707
> chore:  switch to CDS Release Bot

- docker/superset_config.py
Add the ability to manage the TableSchemaView and TabStateView. These missing permissions were resulting in 403 errors to our users trying to create charts and run SQL queries.
> fix: permissions for `WriteData` role

- terragrunt/aws/alarms.tf
Update the CloudWatch error alarm filters to avoid triggering an alarm for user entered query issues.  This is being done so that when a user it using SQL labs and enters a malformed query, it does not alert our team.
Notes:
- This will suppress CloudWatch alarms for logs with `ERROR` in them if they also contain the string `GENERIC_DB_ENGINE_ERROR`.
- The two existing suppressions that had this string are being removed since they're now covered by this more general case.
- This updates 3 CloudWatch alarms as the filter pattern is shared by the 3 ECS services used to run Superset (`superset`, `celery-worker` and `celery-beat`).
> chore: suppress generic PostgresSQL errors

- terragrunt/aws/waf.tf
- terragrunt/env/staging/terragrunt.hcl
Update the Superset IAM roles to include the Data Lake Staging Glue databases.
Also disables the `block` action on the firewall for the BlockedIP rule as there are still several cases of legitimate users being blocked by this.
> fix: add Staging Data Lake IAM roles

- terragrunt/aws/athena.tf
- terragrunt/aws/athena_iam.tf
- terragrunt/aws/variables.tf
- terragrunt/env/prod/terragrunt.hcl
- terragrunt/env/staging/terragrunt.hcl
Update the Superset IAM roles used to access datasets in the Prod and Staging Data Lake accounts.  This change allows fine grained control over the Data Lake accounts that are available to Superset Prod and Staging.
With this configuration, the following permissions will be granted:
1. `Superset Staging`: access to both Prod/Staging Data Lake accounts.
2. `Superset Prod`: access to only Prod Data Lake account.
The reason Staging is allowed access to both Data Lake accounts is so that ad-hoc Prod dataset testing can be performed.
> fix: Superset IAM roles used to access the Data Lake

- terragrunt/aws/athena.tf
Updating the existing Athena data catalog's description is not supported through the API so I'm reverting the description change.
> fix: revert the description change for the data catalog

- .github/workflows/workflow-failure.yml
- terragrunt/aws/athena.tf
Update the workflow failure notifier to sent to the appropriate Staging or Production ops channel, depending on the failed workflow's name.
Also removes the Athena `moved` block as the Terraform state migration has been completed.
> fix: route failed workflow notifications to correct channel

- .github/workflows/docker-deploy-prod.yml
- .github/workflows/docker-deploy-staging.yml
Update the Docker deploy workflows so they use the correct reference to the `main` branch commit that triggered their invocation.
> fix: race condition to retrieve commit SHA

- docker/superset_config.py
Update the Superset config to require SSL connections between the app and database.
- https://github.com/cds-snc/platform-core-services/issues/747
> feat: require SSL for database connection

- docker-compose.yml
- docker/.env.local
- terragrunt/aws/redis.tf
Add a Valkey memcache that we'll use to cache Superset charts and dashboards.  The reason for this change is Valkey is ~33% cheaper than Redis and acts as drop-in replacement.
This change also slightly increases the cache size in Production as we have intermittently seen out-of-memory errors when trying to cache results.
The path for applying this change will be as follows:
1. Create the new cluster.
1. Switch Superset over to new cluster.
1. Delete existing Redis cluster.
- https://github.com/cds-snc/platform-core-services/issues/657
> feat: switch to Valkey caching engine

- terragrunt/aws/cache.tf
The AWS replication group API endpoint is needed for creation of a Valkey memcache cluster.
- #423
> fix: creation of the Valkey memcache cluster

- terragrunt/aws/ecs.tf
Now that the new memcache cluster is up and running, switch over the ECS tasks to use it.  Once this is complete, a final PR will be created to remove the old Redis cluster.
> feat: switch to the fully operational Valkey cluster

- terragrunt/aws/load_balancer.tf
- terragrunt/aws/vpc.tf
Remove the port 80 LB listener.  This was present to upgrade insecure requests to port 443, but modern browsers are doing this already and it is leading to false-positives in our security scanning.
- https://github.com/cds-snc/platform-core-services/issues/709
- https://github.com/cds-snc/platform-core-services/issues/752
> fix: remove port 80 load balancer listener

- terragrunt/env/prod/terragrunt.hcl
- terragrunt/env/staging/terragrunt.hcl
Update the Aurora Serverless min capacity for the database to save money during off-peak use.
ℹ️  Note that in Staging this won't result in a full pause of the database since the ECS service and RDS proxy maintain persistent connections.
> chore: lower min capacity scaling of database

- .github/CODEOWNERS
Update the CODEOWNERS rules so that only the Platform Core Services team can approve PRs.
- https://github.com/cds-snc/platform-core-services/issues/757
> fix: update CODEOWNERS for our team

- terragrunt/aws/route53.tf
- terragrunt/aws/waf.tf
Enable AWS Shield Advanced auto mitigations for the load balancer and hosted zone.
Also removes a Terraform state migration that has been completed.
- https://github.com/cds-snc/platform-core-services/issues/761
> feat: enable AWS Shield Advanced

- .github/workflows/backstage-catalog-helper.yml
- .github/workflows/docker-apply-prod.yml
- .github/workflows/docker-apply-staging.yml
- .github/workflows/docker-deploy-prod.yml
- .github/workflows/docker-deploy-staging.yml
- .github/workflows/docker-pr.yml
- .github/workflows/export_github_data.yml
- .github/workflows/labels.yml
- .github/workflows/ossf-scorecard.yml
- .github/workflows/tf-apply-prod.yml
- .github/workflows/tf-apply-staging.yml
- .github/workflows/tf-plan-prod.yml
- .github/workflows/tf-plan-staging.yml
Update the GitHub action version pinning so that immutable commit SHAs are used.  This will make it more difficult for malicious code to be injected into our workflows.
- https://github.com/cds-snc/platform-core-services/issues/758
> fix: pin GitHub actions to commit SHAs

- terragrunt/aws/alarms.tf
Update the CloudWatch metric filter regex used by the privileged role grant alarm.
- https://github.com/cds-snc/platform-core-services/issues/759
> fix: privileged role grant regular expression

- .github/workflows/tf-apply-prod.yml
- .github/workflows/tf-apply-staging.yml
- .github/workflows/tf-plan-prod.yml
- .github/workflows/tf-plan-staging.yml
- terragrunt/aws/alarms.tf
- terragrunt/aws/variables.tf
Update to use a Sentinel alert to check if a privileged role has been granted.  This is needed because of the limitations of the CloudWatch metric filter regular expressions.
This PR is step one of the change to get the logs into Sentinel.  Once it's running, the new Sentinel alert will be created.
> fix: switch to Sentinel forwarder to capture role grants

- docker/Dockerfile
Remove the `-dev` dependencies as they are not needed to run Superset and are full of vulnerabilities adding noise to our scan results.
- https://github.com/cds-snc/platform-core-services/issues/745
> fix: remove dev dependencies from base image

- docker/Dockerfile
Add the `libecpg-dev` package so that Superset can validate user entered SQL queries.
- https://github.com/cds-snc/platform-core-services/issues/745
> fix: add `ecpg` to validate SQL syntax

- terragrunt/aws/alarms.tf
Update the alarms so that failed thumbnail requests do not trigger a CloudWatch alarm.  These failed requests are retried and non-user impacting.
> chore: suppress thumbnail retrieval error

- terragrunt/aws/alarms.tf
Add a few more alarm suppressions for non-user impacting errors around generating dashboard and chart thumbnails.
> fix: suppress thumbnail cache alarms

- docker/superset_config.py
Add security headers to requests to improve protection against malicious actors successfully gaining access to the service and its data.
This change came about while gathering evidence for SC-23 and discovering that the v5.0.0 release of Superset has disabled CSP headers.
- https://github.com/cds-snc/superset-system-level-security-controls/issues/60
> feat: add security headers

- docker/superset_config.py
Set the default logging format and level.  This is the same default applied by Superset upstream but gives us flexibility in the future and simplifies SA&A evidence collection.
> feat: set the Superset log format and level

- terragrunt/aws/cache.tf
This option is required to enable transit encryption on the cache.
> fix: apply cache changes immediately
